version: '3.1'

services:

  postgres:
    container_name: "db"
    image: postgres:14-alpine
    restart: always
    environment:
      - 'POSTGRES_DB=mian'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - back

  redis:
    container_name: "redis"
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./data/redis:/data

networks:
  back:
    driver: bridge
